#!/usr/bin/env bash
# Single source of truth for agent instructions: ~/dotfiles
# - Claude Code reads ~/.claude/*.md (supports @imports)
# - Codex / Gemini read one flat file (no @import support) -> generated below
set -euo pipefail
D="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

link() {  # link <source> <target>
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  [ -e "$dst" ] && [ ! -L "$dst" ] && mv "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
  ln -sfn "$src" "$dst"
  echo "linked $dst -> $src"
}

# 1. Claude Code: link each file so @imports resolve from either directory
for f in CLAUDE.md RTK.md WAYFINDER-LEANCODE.md IDENTITY.md; do
  link "$D/claude/$f" "$HOME/.claude/$f"
done

# 2. Flat file for agents without @import support
{
  echo "<!-- GENERATED by ~/dotfiles/sync.sh - edit ~/dotfiles/claude/*.md instead -->"
  echo
  for f in IDENTITY.md RTK.md WAYFINDER-LEANCODE.md; do
    cat "$D/claude/$f"
    echo
    echo "---"
    echo
  done
} > "$D/agents/AGENTS.md"
echo "generated $D/agents/AGENTS.md"

link "$D/agents/AGENTS.md" "$HOME/.codex/AGENTS.md"
link "$D/agents/AGENTS.md" "$HOME/.gemini/GEMINI.md"
